[depth]
name = "Depth"

[mono]
name = "Mono"

[oversample]
name = "Oversample"

[simple-channel]
name = "Simple Channel"

[simple-clipper]
name = "Simple Clipper"

[simple-gain]
name = "Simple Gain"

[simple-filter]
name = "Simple Filter"

[simple-tube]
name = "Simple Tube"

[sundara-monitors]
name = "Sundara Monitors"
