[oversample]
name = "Oversample"

[simple-channel]
name = "Simple Channel"

[simple-clipper]
name = "Simple Clipper"

[simple-gain]
name = "Simple Gain"

[simple-filter]
name = "Simple Filter"

[simple-saturation]
name = "Simple Saturation"

[simple-tube]
name = "Simple Tube"
